/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elman.view.admin;

import com.elman.dao.AdminDao;
import com.elman.dao.AdminDaoImpl;
import com.elman.model.Admin;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gahr_bz15
 */
public class AdminPortal extends javax.swing.JFrame {
    AdminDao adImpl = new AdminDaoImpl();
    
   

    /**
     * Creates new form AdminPortal
     */
    public AdminPortal() {
        initComponents();
        showLastLoginDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonPatDetails = new javax.swing.JButton();
        jButtonApp = new javax.swing.JButton();
        jButtonReceptionist = new javax.swing.JButton();
        jButtonDocDetails = new javax.swing.JButton();
        jButtonIndoorPatient = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonIndoorPatient1 = new javax.swing.JButton();
        jLabelLastLoginDateAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(78, 126, 130));
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 255));
        jButton1.setText("Admin Portal ");
        jButton1.setEnabled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonPatDetails.setBackground(new java.awt.Color(0, 204, 255));
        jButtonPatDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonPatDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elman/view/icons/patient.png"))); // NOI18N
        jButtonPatDetails.setText("Patient Details");
        jButtonPatDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonPatDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPatDetailsActionPerformed(evt);
            }
        });

        jButtonApp.setBackground(new java.awt.Color(0, 204, 255));
        jButtonApp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elman/view/icons/appointment.png"))); // NOI18N
        jButtonApp.setText("Appointments");
        jButtonApp.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppActionPerformed(evt);
            }
        });

        jButtonReceptionist.setBackground(new java.awt.Color(0, 204, 255));
        jButtonReceptionist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonReceptionist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elman/view/icons/receptionist.png"))); // NOI18N
        jButtonReceptionist.setText("Receptionist");
        jButtonReceptionist.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonReceptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceptionistActionPerformed(evt);
            }
        });

        jButtonDocDetails.setBackground(new java.awt.Color(0, 204, 255));
        jButtonDocDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDocDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elman/view/icons/doctor.png"))); // NOI18N
        jButtonDocDetails.setText("Doctor Details");
        jButtonDocDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonDocDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocDetailsActionPerformed(evt);
            }
        });

        jButtonIndoorPatient.setBackground(new java.awt.Color(0, 204, 255));
        jButtonIndoorPatient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonIndoorPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elman/view/icons/inPatient.png"))); // NOI18N
        jButtonIndoorPatient.setText("Indoor Patient");
        jButtonIndoorPatient.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonIndoorPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndoorPatientActionPerformed(evt);
            }
        });

        jButtonLogOut.setBackground(new java.awt.Color(204, 0, 0));
        jButtonLogOut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jButtonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elman/view/icons/logout.png"))); // NOI18N
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(255, 51, 51));
        jButtonBack.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elman/view/icons/back.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonIndoorPatient1.setBackground(new java.awt.Color(0, 204, 255));
        jButtonIndoorPatient1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonIndoorPatient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elman/view/icons/outPatient.png"))); // NOI18N
        jButtonIndoorPatient1.setText("Outdoor Patient");
        jButtonIndoorPatient1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonIndoorPatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndoorPatient1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonLogOut))
                            .addComponent(jLabelLastLoginDateAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIndoorPatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPatDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDocDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addComponent(jButtonReceptionist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIndoorPatient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLastLoginDateAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReceptionist, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPatDetails))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApp, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDocDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIndoorPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIndoorPatient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPatDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPatDetailsActionPerformed
       new PatientDetailsAdmin().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButtonPatDetailsActionPerformed

    private void jButtonReceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceptionistActionPerformed
        new ReceptionistDetailsAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonReceptionistActionPerformed

    private void jButtonDocDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocDetailsActionPerformed
     
    }//GEN-LAST:event_jButtonDocDetailsActionPerformed

    private void jButtonAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppActionPerformed
        
    }//GEN-LAST:event_jButtonAppActionPerformed

    private void jButtonIndoorPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndoorPatientActionPerformed
       
    }//GEN-LAST:event_jButtonIndoorPatientActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
      new LoginAdmin().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonIndoorPatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndoorPatient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIndoorPatient1ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new LoginAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonApp;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDocDetails;
    private javax.swing.JButton jButtonIndoorPatient;
    private javax.swing.JButton jButtonIndoorPatient1;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonPatDetails;
    private javax.swing.JButton jButtonReceptionist;
    private javax.swing.JLabel jLabelLastLoginDateAdmin;
    // End of variables declaration//GEN-END:variables

    private void showLastLoginDate() {
        String text = "Last Login Date: ";
        
      Admin admin = new Admin();
       admin = adImpl.getAllAdmin(admin);
        
        boolean result = adImpl.updateLastLoginDateAdmin(admin.getId());
        
        if(jLabelLastLoginDateAdmin.isEnabled()){
         if(!result){
        jLabelLastLoginDateAdmin.setText("Can not update last login date");}
         else if(admin.getLast_login_date()!=null){
             jLabelLastLoginDateAdmin.setText(text+admin.getLast_login_date());
         }
        }
        
      
       
        
        }
      
       
       
       
    }
    


