/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elman.view.admin;

import com.elman.dao.ReceptionistDao;
import com.elman.dao.ReceptionistDaoImpl;
import com.elman.model.Receptionist;
import static java.util.Collections.list;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ReceptionistDetailsAdmin extends javax.swing.JFrame {
    ReceptionistDao reImpl = new ReceptionistDaoImpl();

    public ReceptionistDetailsAdmin() {
        initComponents();
        setTable();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReceptionist = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTableReceptionist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReceptionist);

        jButtonBack.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elman/view/icons/back.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new PatientDetailsForAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistDetailsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReceptionist;
    // End of variables declaration//GEN-END:variables

    private void setTable() {
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
        dtm.addColumn("id");
        dtm.addColumn("First Name");
        dtm.addColumn("Last Name");
        dtm.addColumn("Age");
        dtm.addColumn("Gender");
        dtm.addColumn("Address");
        dtm.addColumn("City");
        dtm.addColumn("Phone Number");
        dtm.addColumn("Marital Status");
        
                
        Receptionist receptionist = new Receptionist();

        List<Receptionist> list = reImpl.getAllReceptionist(receptionist);
        
        for(int i = 0;i<list.size();i++){
        
            dtm.addRow(new Object[]{1,list.get(i).getFirst_name(),list.get(i).getLast_name(),list.get(i).getAge(),list.get(i).getGender(),list.get(i).getAddress(),list.get(i).getCity(),list.get(i).getPhoneNumber(),list.get(i).getMaritalStatus()});
            
        }
     
        jTableReceptionist.setModel(dtm);
        
         jTableReceptionist.getColumnModel().getColumn(0).setPreferredWidth(12);
          jTableReceptionist.getColumnModel().getColumn(1).setPreferredWidth(78);
          jTableReceptionist.getColumnModel().getColumn(2).setPreferredWidth(80);
          jTableReceptionist.getColumnModel().getColumn(3).setPreferredWidth(22);
          jTableReceptionist.getColumnModel().getColumn(4).setPreferredWidth(50);
          jTableReceptionist.getColumnModel().getColumn(5).setPreferredWidth(132);
          jTableReceptionist.getColumnModel().getColumn(6).setPreferredWidth(85);
          jTableReceptionist.getColumnModel().getColumn(7).setPreferredWidth(110);
          jTableReceptionist.getColumnModel().getColumn(8).setPreferredWidth(85);
        
    }
}
